USE SutekiShop
CREATE TABLE dbo.Referer (
	RefererId int NOT NULL IDENTITY (1, 1),
	Name varchar(1024) NOT NULL,
	Position int NOT NULL,
	IsActive bit NOT NULL
) ON [PRIMARY]

ALTER TABLE dbo.Referer ADD CONSTRAINT PK_Referer PRIMARY KEY CLUSTERED (
	Id
) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]